### ISSUE TITLE
Schrödinger Equation

### ISSUE THREAD

**Issue by soltaniehha** [GDS-Education-Community-of-Practice/DSECOP#6]
This module can be used can be used for a Quantum Mechanics course. The module will begin with
introduction to the Schrödinger Equation including a tutorial on analytical solutions for different toy
systems such as Particle-In-A-Box, Quantum Harmonic Oscillator etc. The second portion of this module
will consist of a brief primer on numerical techniques for solving differential equations. Finally, deep
learning will be introduced with code examples and students would be expected to compare the numerical
and deep learning methods with the analytical solution for a system of their choice.

**Comment by karanprime** [comment]
ToDos before workshop:
- [ ] Add self-contained PINN implementation in Keras instead of Modulus framework
- [ ] Add other systems for the time dependent schrodinger equation
- [ ] Add analytical solutions
- [ ] Add numerical solutions
- [ ] Explain advantages and disadvantages of ML based solutions
- [ ] Elaborate on exercises
- [ ] Add further resources
